=== FraMog/ProgettoTesiDiLaureaTriennale/HTTPSServer/WebContent/PositioningXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Root">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NonLinearAd" maxOccurs="unbounded"
					minOccurs="1" type="adPositioningNonLinear">
				</xs:element>
				<xs:element name="companionAds" minOccurs="1"  maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CompanionAd" maxOccurs="unbounded"
								minOccurs="0" type="adPositioning">
							</xs:element>
							
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="adPositioning">
		<xs:attribute type="xs:decimal" name="positionX" use="required"></xs:attribute>
		<xs:attribute type="xs:decimal" name="positionY" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="adPositioningNonLinear">
		<xs:complexContent>
			<xs:extension base="adPositioning">
				<xs:sequence>
					<xs:element name="Id" type="xs:string" minOccurs="1">
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
</xs:schema>

=== FraMog/ProgettoTesiDiLaureaTriennale/HTTPSServer/WebContent/Positioning.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<Root xmlns="https://localhost:8443/HTTPSServer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://localhost:8443/HTTPSServer PositioningXSD.xsd">
	<NonLinearAd>
		<!-- 640-157.34 -->
		<!-- <positionX>482.66</positionX> -->
		<positionX>640</positionX>
		<positionY>0</positionY>
		<Id>1</Id>
		<CompanionAds>
			<CompanionAd>
				<positionX>0</positionX>
				<!-- 360-112.67 -->
				<positionY>247.33</positionY>
			</CompanionAd>
		</CompanionAds>
	</NonLinearAd>


	<NonLinearAd>
		<positionX>0</positionX>
		<positionY>191</positionY>
		<Id>2</Id>
	</NonLinearAd>



</Root>

=== FraMog/ProgettoTesiDiLaureaTriennale/HTTPSServer/WebContent/positioningXML/Positioning.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<Root xmlns="http://localhost/HTTPSServer/positioningXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://localhost/HTTPSServer/positioningXML PositioningXSD.xsd">
	
	<!-- Id dell'annuncio Ã¨ lo stesso indicato per l'annuncio principale nei rispettivi VAST xml -->
	
	
	<!-- Museo1.xml -->
	<NonLinearAd>
		<!-- 640-157.34 -->
		<!-- <positionX>482.66</positionX> -->
		<positionX>640</positionX>
		<positionY>360</positionY>
		<Id>Museo1</Id>
	</NonLinearAd>
	
	<!-- Museo2.xml -->
	<NonLinearAd>
		<!-- 640-157.34 -->
		<!-- <positionX>482.66</positionX> -->
		<positionX>0</positionX>
		<positionY>0</positionY>
		<Id>Museo2</Id>
	</NonLinearAd>
	
	
	<!-- Filosofi.xml -->
	<NonLinearAd>
		<!-- 640-157.34 -->
		<!-- <positionX>482.66</positionX> -->
		<positionX>0</positionX>
		<positionY>0</positionY>
		<Id>Filosofi</Id>
	</NonLinearAd>
	
	
	<NonLinearAd>
		<!-- 640-157.34 -->
		<!-- <positionX>482.66</positionX> -->
		<positionX>640</positionX>
		<positionY>0</positionY>
		<Id>FanciullaDiAnzio</Id>
		<CompanionAds>
			<CompanionAd>
				<positionX>0</positionX>
				<!-- 360-112.67 -->
				<positionY>247.33</positionY>
			</CompanionAd>
		</CompanionAds>
	</NonLinearAd>


	<NonLinearAd>
		<positionX>0</positionX>
		<positionY>191</positionY>
		<Id>Ermafrodito</Id>
	</NonLinearAd>



</Root>
